import React from 'react'
import styles from '../assets/styles/pages/policy.module.css'

export default function Policy() {
  return (
    <div className={styles['policy-text']}>
      <h5>What is a cookie?</h5>
      <p>
        A cookie is a piece of data sent to your device from a website which is
        stored on your browser or the hard drive of your computer if you agree.
        Cookies are uniquely assigned to you and can only be read by a web
        server in the domain that issued the cookie to you, and this information
        may also be shared with third parties/other websites. This means the
        website can recognise your device if you return to the same website. For
        example, if you register with on our websites or download one of our
        applications, a cookie helps us to recall your information on subsequent
        visits. This simplifies the process of recording your personal
        information, such as your email address. When you return to our
        websites, the information you previously provided can be retrieved, so
        you can easily use the features that you customized.
      </p>
      <p>
        Cookies are not used to run programs or deliver viruses to your
        computer. Some cookies expire at the end of your website session; others
        remain on your computer for longer.
      </p>
      <h5>What is a pixel?</h5>
      <p>
        Tracking pixels are transparent graphic images (sometimes called web
        beacons or tracking beacons) that are placed on certain pages of our
        website. A tracking pixel collects certain electronic information from
        your webpage’s header, such as your IP address or browser and your
        location, which may be forwarded to an advertising platform for the
        purpose of providing advertising to you that is based on your personal
        interests. We also use tracking pixels provided by certain tools to
        allow us to see how you interact with our email marketing or website.
      </p>
      <h5>Cookies, pixels and similar technologies used on our website</h5>
      <p>
        The exact names of cookies we use on our websites may change over time,
        however, the descriptions below set out the types of cookies that
        operate on our websites. You can obtain an up to date list of the
        cookies we use by contacting us at privacy@scandit.com
      </p>
      <ul>
        <li>
          Strictly necessary cookies. These are cookies that are required for
          the operation of our websites or provide services explicitly requested
          by you. They include, for example, cookies that enable you to log into
          secure areas of our websites or apps.
        </li>
        <li>
          Analytical/performance cookies. They allow us to recognise and count
          the number of visitors and to see how visitors move around our
          websites when they are using it. This helps us to improve the way our
          websites work, for example, by ensuring that users are finding what
          they are looking for easily.
        </li>
        <li>
          Functionality cookies. These are used to recognise you when you return
          to our websites. This enables us to personalise our content for you
          and remember your preferences (for example, your choice of language or
          region).
        </li>
        Targeting cookies/tracking pixels. These record your visit to our
        website, the pages you have visited and the links you have followed. We
        will use this information to make our website and the advertising
        displayed to you more relevant to your interests. We may also share this
        information with third parties for this purpose. We may combine the
        information we collect through cookies and pixel tags with other
        information we have collected from you, based on our legitimate
        interest, as this information may be used to improve our website,
        personalize your online experience, tailor our communications with you,
        determine the effectiveness of our advertising, and for other internal
        business purposes.
      </ul>
      <p>
        Google Analytics. We use Google Analytics. The information generated by
        the Google Analytics cookie (including your IP address) will be
        transmitted to and stored by Google on servers in the United States.
        Google will use this information for the purpose of evaluating your use
        of the websites, compiling reports on activity and providing other
        services relating to activity and internet usage. For more information
        on the cookies set by Google Analytics see: Cookies and Google
        Analytics. You may opt out of being tracked by Google Analytics across
        all websites – to do so please go to
        https://tools.google.com/dlpage/gaoptout.
      </p>
      <p>
        We may also use other technologies with similar functionality to
        cookies, such as web beacons and tracking URLs, including in emails to
        determine whether a recipient opened the email or accessed a certain
        link.
      </p>
      <h5>How to control or delete cookies</h5>
      <p>
        You have the ability to accept or decline cookies. Most web browsers
        automatically accept cookies, but you can usually modify your browser
        setting to decline cookies if you prefer. You can also set your browser
        to alert you when a website sets or accesses cookies. The ‘Help’
        function within your browser should tell you how to do this.
      </p>
      <p>
        Links providing information regarding how you can control access to
        cookies for the major browsers are provided below:
      </p>
      <p>
        Microsoft Edge:
        https://privacy.microsoft.com/en-us/windows-10-microsoft-edge-and-privacy
        Internet Explorer:
        https://support.microsoft.com/en-gb/help/17442/windows-internet-explorer-delete-manage-cookies
        Chrome: https://support.google.com/chrome/answer/95647?hl=en-GB Firefox:
        https://support.mozilla.org/en-US/kb/delete-browsing-search-download-history-firefox
        Safari:
        https://support.apple.com/es-es/guide/safari/manage-cookies-and-website-data-sfri11471/mac
        Alternatively, you may wish to visit www.aboutcookies.org which contains
        comprehensive information on how to do this on a wide variety of
        browsers. You will also find details on how to delete cookies from your
        machine as well as more general information about cookies. In addition,
        the Digital Advertising Alliance (DAA) also provides a website that
        allows you to opt-out of cookies (and/or pixels) for various
        participating companies at www.optout.aboutads.info. The Network
        Advertising Initiative also provides an opt-out page at
        http://optout.networkadvertising.org/?c=1. It is also possible to
        opt-out of Google’s Ad Personalisation here:
        https://adssettings.google.com/authenticated?hl=en#display_optout
      </p>
      <p>
        If you wish to view a cookie’s code, just open your cookie file in your
        browser and click on a cookie to open it. You’ll see a short string of
        text and numbers. The numbers are your identification card, which can
        only be seen by the server that gave you the cookie. For information on
        how to do this on the browser of your mobile phone you will need to
        refer to your device manual.
      </p>
      <p>
        Please be aware that restricting cookies may impact on the functionality
        of our websites.
      </p>
      <p>
        Please note that third parties (including, for example, advertising
        networks and providers of external services like web traffic analysis
        services) may also use cookies, over which we have no control. These
        cookies are likely to be analytical/performance cookies or targeting
        cookies.
      </p>
      <p>Duration of Cookies</p>
      <p>
        Session cookies – These cookies are temporary and expire once you close
        your browser (or once your session ends). Persistent cookies — This
        category encompasses all cookies that remain until you erase them or
        your browser does, depending on the cookie’s expiration date. All
        persistent cookies have an expiration date written into their code, but
        their duration can vary for each category or specific cookie. If you
        require more information regarding the duration of a particular cookie
        used by Apotek please contact us on the email below.
      </p>
      <p>
        If you have any queries about this policy, please contact
        privacy@apotek.se
      </p>
    </div>
  )
}

Policy.title = 'Policy'
